# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d80a4ca4d4ca5bc7e0bfa14a695abbd146eec2f088ebaf8151fb53340d93d88af6f9d1cf9249745093f6900b2088e10dc7d0df4b0ef254a270192261805a99a

test:
  secret_key_base: 92ee51801fb11f214943b8c6a373e8e843f837905f2ac7af17baea9212f4119f4236f61b4714500b8405c0ffc8d734a1bd0ce1d35029534b7221f58a9885a73e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
